# Generated by Django 4.2.29 on 2026-04-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '在庫(本)',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='タイトル未入力', max_length=100, unique=True, verbose_name='タイトル')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='値段')),
                ('status', models.CharField(choices=[('order', '発注待ち'), ('waiting', '陳列待ち'), ('completion', '陳列済み')], max_length=20, verbose_name='状態')),
                ('quantity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.book_stock', verbose_name='在庫(本)')),
            ],
            options={
                'verbose_name': '本データ',
                'db_table': 'book',
            },
        ),
    ]
