# Generated by Django 4.2.29 on 2026-04-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_book',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.book')),
                ('file_size', models.FloatField(default=0.0, verbose_name='ファイルサイズ(mb)')),
                ('download_url', models.URLField(blank=True, null=True, verbose_name='ダウンロードURL')),
            ],
            options={
                'verbose_name': '電子書籍',
            },
            bases=('accounts.book',),
        ),
    ]
