# Generated by Django 4.2.29 on 2026-04-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本'},
        ),
        migrations.AlterModelOptions(
            name='book_stock',
            options={'verbose_name': '在庫'},
        ),
        migrations.AlterModelTable(
            name='book_stock',
            table=None,
        ),
    ]
