# Generated by Django 4.2.29 on 2026-04-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_e_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='accounts.author', verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('order', '発注待ち'), ('waiting', '陳列待ち'), ('completion', '陳列済み')], default='発注待ち', max_length=20, verbose_name='状態'),
        ),
    ]
